### ISSUE TITLE
Docker Development Environment

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/Odysseus#30]
So for Odyssey stuff we are dealing with a lot of moving parts that we don't want developers to have to deploy on their own machines locally. We already have a somewhat simple dockerfile but we need to modify it to contain tools that would be helpful during development.

Biggest thing is having an MQTT server running in this that we can use to play around with for connection. Installing Python, nodejs, and Rust in it would also be nice so that we can compile stuff inside of it (might be a ginormous docker container lmao)

**Comment by jr1221** [comment]
Moved to Odyssey-Base
https://github.com/Northeastern-Electric-Racing/Odyssey-Base/issues/14
