### ISSUE TITLE
Repo Cleanup

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/Odysseus#41]
At the beginning of this whole endeavor, the scope of all the different repos wasn't super clear since this was fairly uncharted territory, but I think we have a fairly good idea of what the final product will look like now. In terms of this repo's place in the whole system, I think that we will want to:
1. Deprecate a lot of the HaLow startup scripting, as is not needed for buildroot (probably keep on a separate branch but delete)
2. Parse through other directories, keeping what is relevant and deleting any unused files
3. Update all necessary README's, improving documentation for new people jumping on the project
4. Moving Odysseus and other buildroot stuff to top level directory, making the top level only contain `odysseus_ext_tree`, `scripts` (for MQTT sample pubs/subs, diagnostics, and data scraping scripts), and `buildroot` (the submodule)
5. Potentially just renaming this repo to `Odysseus` or rethink naming

**Comment by jr1221** [comment]
Kinda note to self: Leaving this open as reminder that odysseus folder should be top level.  All other items mentioned here have been included in various PRs.
